Python 3.13.7 (tags/v3.13.7:bcee1c3, Aug 14 2025, 14:15:11) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> 
... 
... print("Program starting.")
... print("Estimate how many minutes you spent on programming...\n")
... 
... 
... t1 = int(input("A1_T1: "))
... t2 = int(input("A1_T2: "))
... t3 = int(input("A1_T3: "))
... t4 = int(input("A1_T4: "))
... t5 = int(input("A1_T5: "))
... t6 = int(input("A1_T6: "))
... t7 = int(input("A1_T7: "))
... 
... 
... total = t1 + t2 + t3 + t4 + t5 + t6 + t7
... 
... 
... average = round(total / 7, 2)
... 
... average_int = int(round(total / 7, 0))
... 
... print()
... print(f"In total you spent {total} minutes on programming.")
... print(f"Average per task was {average} min and same rounded to the nearest integer {average_int} min.\n")
... 
... print("Program ending.")
